name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 瑙﹀彂鍚姩寮€濮嬬紪璇?
      id: gitpush
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        tmpdir="$(mktemp -d)"
        UPLOAD="$GITHUB_WORKSPACE/${tmpdir#*.}"

        # 鍏嬮殕浠撳簱
        git clone --depth=1 -b ${GIT_REFNAME} https://user:${REPO_TOKEN}@github.com/${GIT_REPOSITORY}.git $UPLOAD
        cd $UPLOAD
        git reset --hard HEAD
        cd ${GITHUB_WORKSPACE}

        # 娓呯悊鍜屽鍒舵枃浠?
        [[ -d "$UPLOAD/build/${FOLDER_NAME}" ]] && rm -rf "$UPLOAD/build/${FOLDER_NAME}"
        cp -Rf "$CONFIG_TXT" "$MYCONFIG_FILE"
        cp -Rf "$COMPILE_PATH" "$UPLOAD/build/$FOLDER_NAME"
        [[ -d "$UPLOAD/build/common" ]] && rm -rf "$UPLOAD/build/common"
        cp -Rf "$GITHUB_WORKSPACE/.github/workflows/compile.yml" "$UPLOAD/.github/workflows/compile.yml"

        # 鍒涘缓鐩稿叧鐩綍鍜屾枃浠?
        mkdir -p "$UPLOAD/build/${FOLDER_NAME}/relevance"
        echo "${SOURCE}-${REPO_BRANCH}-${CONFIG_FILE}-$(date +%Y骞?m鏈?d鍙?H鏃?M鍒?S绉?" > "$UPLOAD/build/${FOLDER_NAME}/relevance/start"
        cp -Rf "$COMPILE_PATH/relevance/settings.ini" "$UPLOAD/build/${FOLDER_NAME}/relevance/settings.ini"
        echo "ERRUN_NUMBER=${RUN_NUMBER}" >> "$UPLOAD/build/${FOLDER_NAME}/relevance/settings.ini"

        # 淇敼缂栬瘧閰嶇疆鏂囦欢
        YML_PATH="$UPLOAD/.github/workflows/compile.yml"
        PATHS="build/${FOLDER_NAME}/relevance/start"
        sed -i "/branches:/,/paths:/s|- .*|- ${GIT_REFNAME}|" "$YML_PATH"
        sed -i "/paths:/,/matrix:/s@- .*@- '${PATHS//@/\\@}'@" "$YML_PATH"
        sed -i "/matrix:/,/^ *target:/s/target:.*/target: [${FOLDER_NAME}]/" "$YML_PATH"

        # 鎻愪氦骞舵帹閫?
        BANBEN_SHUOMING="缂栬瘧-${FOLDER_NAME}-${LUCI_EDITION}-${TARGET_PROFILE}鍥轰欢"
        chmod -R +x "$UPLOAD"
        cd "$UPLOAD"
        find "$UPLOAD" -type f -size +100M -exec rm -f {} \; || true
        git status
        git add .
        git commit -m "${BANBEN_SHUOMING}"
        PUSH_SUCCESS=false
        RETRY_COUNT=0
        MAX_RETRIES=5
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          RETRY_COUNT=$((RETRY_COUNT+1))
          echo "灏濊瘯鎺ㄩ€?(${RETRY_COUNT}/${MAX_RETRIES})..."
          # 姣忔閲嶈瘯鍓嶉噸缃瓾EAD骞堕噸鏂版坊鍔犳枃浠?
          if [ $RETRY_COUNT -gt 1 ]; then
             echo "閲嶇疆HEAD骞堕噸鏂版坊鍔犳枃浠?.."
             git reset --hard HEAD
             git add .
          fi
          if git push --force "https://${REPO_TOKEN}@github.com/${GIT_REPOSITORY}" HEAD:${GIT_REFNAME}; then
             PUSH_SUCCESS=true
             break
          else
             echo "鎺ㄩ€佸け璐ワ紝灏濊瘯鎭㈠..."
             # 娓呴櫎鍙兘鎹熷潖鐨勭紦瀛?
             git gc --prune=now
             git remote prune origin
             # 澧炲姞闅忔満寤惰繜锛岄伩鍏嶆寔缁嘲鍊艰姹?
             DELAY=$((RANDOM % 5 + 2))
             echo "绛夊緟${DELAY}绉掑悗閲嶈瘯..."
             sleep $DELAY
          fi
        done

        # 妫€鏌ユ帹閫佺粨鏋?
        if [ "$PUSH_SUCCESS" = false ]; then
           echo -e "\033[31m 瑙﹀彂缂栬瘧澶辫触,璇峰嬁鑳′贡淇敼compile.yml鏂囦欢 \033[0m"
           exit 1
        else
           echo -e "\033[32m 瑙﹀彂缂栬瘧${FOLDER_NAME}-${LUCI_EDITION}-${TARGET_PROFILE}鎴愬姛 \033[0m"
        fi

    - name: 淇℃伅閫氱煡鐨勬椂闂?
      if: steps.gitpush.outcome == 'success'
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        echo "TZ_Message=$(date +%Y骞?m鏈?d鍙?H鏃?M鍒?" >> "${GITHUB_ENV}"

    - name: Telegram鎴杙ushplus淇℃伅閫氱煡
      if: env.PUSH_PLUS_TOKEN && env.INFORMATION_NOTICE == 'PUSH' && steps.gitpush.outcome == 'success' || env.TELEGRAM_BOT_TOKEN && env.INFORMATION_NOTICE == 'TG' && steps.gitpush.outcome == 'success'
      shell: bash
      run: |
        if [[ "${{ env.INFORMATION_NOTICE }}" == "TG" ]]; then
           curl -s -X POST -H "Content-Type: application/json" -d '{"chat_id":"${{env.TELEGRAM_CHAT_ID}}", "text":"瑙﹀彂鍚姩${{env.SOURCE}}-${{env.LUCI_EDITION}}锛岀紪璇?{{env.TARGET_PROFILE}}鍥轰欢锛岃鑰愬績绛夊緟...... 馃構锛?${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})锛?{{env.TZ_Message}}馃拹"}' "https://api.telegram.org/bot${{env.TELEGRAM_BOT_TOKEN}}/sendMessage"
        fi
        if [[ "${{ env.INFORMATION_NOTICE }}" == "PUSH" ]]; then
           curl -s -X POST -H "Content-Type: application/json" -d '{"token":"${{env.PUSH_PLUS_TOKEN}}","title":"瑙﹀彂鍚姩${{env.SOURCE}}-${{env.LUCI_EDITION}}","content":"缂栬瘧${{env.TARGET_PROFILE}}鍥轰欢锛岃鑰愬績绛夊緟...... 馃構锛?${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})锛?{{env.TZ_Message}}馃拹"}' "https://www.pushplus.plus/send"
        fi
branding:
  icon: "terminal"
  color: "gray-dark"
