name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    # 妫€鏌ootfs.tar.gz鏄惁瀛樺湪
    - name: 妫€鏌ootfs.tar.gz鏄惁瀛樺湪
      shell: bash
      run: |
        cd "${HOME_PATH}"
        if [[ -n "$(find "${FIRMWARE_PATH}" -maxdepth 1 -name '*rootfs.tar.gz' -print -quit)" ]]; then
           mkdir -p "${HOME_PATH}/targz"
           cp -Rf "${FIRMWARE_PATH}"/*rootfs.tar.gz "${HOME_PATH}/targz/${SOURCE}-armvirt-64-default-rootfs.tar.gz"
        else
           echo -e "\033[31m 娌″彂鐜癮rmvirt-64-default-rootfs.tar.gz鍖呭瓨鍦?\033[0m\n"
           echo "PACKAGING_FIRMWARE=false" >> "${GITHUB_ENV}"
        fi

    # 灏唕ootfs.tar.gz鍙戝竷鍒皉eleases鐨則argz
    - name: 灏唕ootfs.tar.gz鍙戝竷releases鐨則argz
      id: targz
      if: env.BENDI_VERSION == '2'
      uses: ncipollo/release-action@v1
      with:
        name: rootfs.tar.gz
        tag: targz
        token: ${{ env.REPO_TOKEN }}
        artifacts: ${{ env.HOME_PATH }}/targz/*rootfs.tar.gz
        allowUpdates: true
        replacesArtifacts: true
        body: armsr_rootfs_tar_gz鎵撳寘浣跨敤鐨剅ootfs.tar.gz鍖?

    - name: 妫€鏌ュ彉閲忔槸鍚﹀瓨鍦?
      shell: bash
      run: |
        cd "${HOME_PATH}"
        if [[ "${BENDI_VERSION}" == "2" ]] && [[ "${{ steps.targz.outcome }}" == "success" ]]; then
           echo -e "\n\033[32m ${SOURCE}-armvirt-64-default-rootfs.tar.gz宸插彂甯冨埌鍚嶇О涓簍argz鐨剅eleases \033[0m"
           echo -e "\033[33m 鎮ㄥ彲浠ラ殢鏃跺啀娆℃墦鍖呬娇鐢?\033[0m\n"
        fi

        if [[ "${BENDI_VERSION}" == "2" ]] && [[ "${PACKAGING_FIRMWARE}" == "false" ]]; then
           echo -e "\n\033[31m 鑷姩鎵撳寘绋嬪簭娌″紑鍚?灏嗕笉浼氳繘琛岃嚜鍔ㄦ墦鍖?\033[0m\n"
        fi
        
        if [[ -z "${amlogic_model}" ]] && [[ "${PACKAGING_FIRMWARE}" == "true" ]]; then
           echo -e "\033[31m amlogic_model鍊间笉瀛樺湪 \033[0m"
           exit 1
        fi
        if [[ -z "${amlogic_kernel}" ]] && [[ "${PACKAGING_FIRMWARE}" == "true" ]]; then
           echo -e "\033[31m amlogic_kernel鍊间笉瀛樺湪 \033[0m"
           exit 1
        fi
        if [[ -z "${auto_kernel}" ]] && [[ "${PACKAGING_FIRMWARE}" == "true" ]]; then
           echo -e "\033[31m auto_kernel鍊间笉瀛樺湪 \033[0m"
           exit 1
        fi
        if [[ -z "${openwrt_size}" ]] && [[ "${PACKAGING_FIRMWARE}" == "true" ]]; then
           echo "openwrt_size=1024" >> "${GITHUB_ENV}"
        fi
        if [[ -z "${kernel_usage}" ]] && [[ "${PACKAGING_FIRMWARE}" == "true" ]]; then
           echo -e "\033[31m kernel_usage鍊间笉瀛樺湪 \033[0m"
           exit 1
        fi

    # 鎵撳寘armsr_rootfs_tar_gz
    - name: 鎵撳寘aarch64绯诲垪鍥轰欢
      id: dabao
      if: env.PACKAGING_FIRMWARE == 'true'
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/targz/*rootfs.tar.gz
        openwrt_board: ${{ env.amlogic_model }}
        openwrt_kernel: ${{ env.amlogic_kernel }}
        auto_kernel: ${{ env.auto_kernel }}
        kernel_repo: ${{ env.kernel_repo }}
        kernel_usage: ${{ env.kernel_usage }}
        openwrt_size: ${{ env.openwrt_size }}
        builder_name: ${{ env.builder_name }}

    # 鎵撳寘淇℃伅
    - name: 鎵撳寘淇℃伅
      if: steps.dabao.outcome == 'success'
      shell: bash
      run: |
        cd "${HOME_PATH}"
        echo "DABAO_MESSAGE=銆佹墦鍖? >> "${GITHUB_ENV}"
        rm -rf "${PACKAGED_OUTPUTPATH}"/*.sha

    # 鎵撳寘鍚庣殑鍥轰欢鏀惧洖鍘熶綅
    - name: 鎵撳寘鍚庣殑鍥轰欢鏀惧洖鍘熶綅
      if: steps.dabao.outcome == 'success'
      shell: bash
      run: |
        cd "${HOME_PATH}"
        if [[ -d "${PACKAGED_OUTPUTPATH}" ]]; then
           cp -Rf "${FIRMWARE_PATH}"/* "${PACKAGED_OUTPUTPATH}"
        fi
        echo "FIRMWARE_PATH=${PACKAGED_OUTPUTPATH}" >> "${GITHUB_ENV}"
        if [[ -n "${TARGET_BOARD}" ]]; then
           echo "TARGET_PROFILE_IMG=${TARGET_BOARD}-img" >> "${GITHUB_ENV}"
        else
           echo "TARGET_PROFILE_IMG=armsr-img" >> "${GITHUB_ENV}"
        fi
branding:
  icon: "terminal"
  color: "gray-dark"
